// Code generated by protoc-gen-go. DO NOT EDIT.
// source: banana.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameStatus int32

const (
	GameStatus_UNKNOWN             GameStatus = 0
	GameStatus_WAITING_FOR_PLAYERS GameStatus = 1
	GameStatus_IN_PROGRESS         GameStatus = 2
	GameStatus_FINISHED            GameStatus = 3
)

var GameStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "WAITING_FOR_PLAYERS",
	2: "IN_PROGRESS",
	3: "FINISHED",
}

var GameStatus_value = map[string]int32{
	"UNKNOWN":             0,
	"WAITING_FOR_PLAYERS": 1,
	"IN_PROGRESS":         2,
	"FINISHED":            3,
}

func (x GameStatus) String() string {
	return proto.EnumName(GameStatus_name, int32(x))
}

func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{0}
}

type Word_Orientation int32

const (
	Word_UNKNOWN    Word_Orientation = 0
	Word_HORIZONTAL Word_Orientation = 1
	Word_VERTICAL   Word_Orientation = 2
)

var Word_Orientation_name = map[int32]string{
	0: "UNKNOWN",
	1: "HORIZONTAL",
	2: "VERTICAL",
}

var Word_Orientation_value = map[string]int32{
	"UNKNOWN":    0,
	"HORIZONTAL": 1,
	"VERTICAL":   2,
}

func (x Word_Orientation) String() string {
	return proto.EnumName(Word_Orientation_name, int32(x))
}

func (Word_Orientation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{28, 0}
}

type NewGameRequest struct {
	// What to name the game.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewGameRequest) Reset()         { *m = NewGameRequest{} }
func (m *NewGameRequest) String() string { return proto.CompactTextString(m) }
func (*NewGameRequest) ProtoMessage()    {}
func (*NewGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{0}
}

func (m *NewGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameRequest.Unmarshal(m, b)
}
func (m *NewGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameRequest.Marshal(b, m, deterministic)
}
func (m *NewGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameRequest.Merge(m, src)
}
func (m *NewGameRequest) XXX_Size() int {
	return xxx_messageInfo_NewGameRequest.Size(m)
}
func (m *NewGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameRequest proto.InternalMessageInfo

func (m *NewGameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NewGameResponse struct {
	// The unique identifier for the game.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewGameResponse) Reset()         { *m = NewGameResponse{} }
func (m *NewGameResponse) String() string { return proto.CompactTextString(m) }
func (*NewGameResponse) ProtoMessage()    {}
func (*NewGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{1}
}

func (m *NewGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameResponse.Unmarshal(m, b)
}
func (m *NewGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameResponse.Marshal(b, m, deterministic)
}
func (m *NewGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameResponse.Merge(m, src)
}
func (m *NewGameResponse) XXX_Size() int {
	return xxx_messageInfo_NewGameResponse.Size(m)
}
func (m *NewGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameResponse proto.InternalMessageInfo

func (m *NewGameResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListGamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGamesRequest) Reset()         { *m = ListGamesRequest{} }
func (m *ListGamesRequest) String() string { return proto.CompactTextString(m) }
func (*ListGamesRequest) ProtoMessage()    {}
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{2}
}

func (m *ListGamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGamesRequest.Unmarshal(m, b)
}
func (m *ListGamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGamesRequest.Marshal(b, m, deterministic)
}
func (m *ListGamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGamesRequest.Merge(m, src)
}
func (m *ListGamesRequest) XXX_Size() int {
	return xxx_messageInfo_ListGamesRequest.Size(m)
}
func (m *ListGamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGamesRequest proto.InternalMessageInfo

type ListGamesResponse struct {
	Games                []*Game  `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGamesResponse) Reset()         { *m = ListGamesResponse{} }
func (m *ListGamesResponse) String() string { return proto.CompactTextString(m) }
func (*ListGamesResponse) ProtoMessage()    {}
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{3}
}

func (m *ListGamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGamesResponse.Unmarshal(m, b)
}
func (m *ListGamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGamesResponse.Marshal(b, m, deterministic)
}
func (m *ListGamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGamesResponse.Merge(m, src)
}
func (m *ListGamesResponse) XXX_Size() int {
	return xxx_messageInfo_ListGamesResponse.Size(m)
}
func (m *ListGamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGamesResponse proto.InternalMessageInfo

func (m *ListGamesResponse) GetGames() []*Game {
	if m != nil {
		return m.Games
	}
	return nil
}

type GamesList struct {
	Games                []*Game  `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamesList) Reset()         { *m = GamesList{} }
func (m *GamesList) String() string { return proto.CompactTextString(m) }
func (*GamesList) ProtoMessage()    {}
func (*GamesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{4}
}

func (m *GamesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamesList.Unmarshal(m, b)
}
func (m *GamesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamesList.Marshal(b, m, deterministic)
}
func (m *GamesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamesList.Merge(m, src)
}
func (m *GamesList) XXX_Size() int {
	return xxx_messageInfo_GamesList.Size(m)
}
func (m *GamesList) XXX_DiscardUnknown() {
	xxx_messageInfo_GamesList.DiscardUnknown(m)
}

var xxx_messageInfo_GamesList proto.InternalMessageInfo

func (m *GamesList) GetGames() []*Game {
	if m != nil {
		return m.Games
	}
	return nil
}

type Game struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               GameStatus `protobuf:"varint,3,opt,name=status,proto3,enum=GameStatus" json:"status,omitempty"`
	PlayerCount          int32      `protobuf:"varint,4,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{5}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Game) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Game) GetStatus() GameStatus {
	if m != nil {
		return m.Status
	}
	return GameStatus_UNKNOWN
}

func (m *Game) GetPlayerCount() int32 {
	if m != nil {
		return m.PlayerCount
	}
	return 0
}

type StartGameRequest struct {
	// The unique identifier for the game to start.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{6}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

func (m *StartGameRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StartGameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameResponse) Reset()         { *m = StartGameResponse{} }
func (m *StartGameResponse) String() string { return proto.CompactTextString(m) }
func (*StartGameResponse) ProtoMessage()    {}
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{7}
}

func (m *StartGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameResponse.Unmarshal(m, b)
}
func (m *StartGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameResponse.Marshal(b, m, deterministic)
}
func (m *StartGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameResponse.Merge(m, src)
}
func (m *StartGameResponse) XXX_Size() int {
	return xxx_messageInfo_StartGameResponse.Size(m)
}
func (m *StartGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameResponse proto.InternalMessageInfo

type JoinGameRequest struct {
	// The unique identifier for the game to join.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the player joining the game.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// This can be set if a player is re-joining a game they're already in, it'll
	// attach the user to the same session.
	PlayerId             string   `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGameRequest) Reset()         { *m = JoinGameRequest{} }
func (m *JoinGameRequest) String() string { return proto.CompactTextString(m) }
func (*JoinGameRequest) ProtoMessage()    {}
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{8}
}

func (m *JoinGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGameRequest.Unmarshal(m, b)
}
func (m *JoinGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGameRequest.Marshal(b, m, deterministic)
}
func (m *JoinGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGameRequest.Merge(m, src)
}
func (m *JoinGameRequest) XXX_Size() int {
	return xxx_messageInfo_JoinGameRequest.Size(m)
}
func (m *JoinGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGameRequest proto.InternalMessageInfo

func (m *JoinGameRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JoinGameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JoinGameRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type GameUpdate struct {
	// Types that are valid to be assigned to Update:
	//	*GameUpdate_CurrentStatus
	//	*GameUpdate_PlayerUpdate
	//	*GameUpdate_GameStarted
	//	*GameUpdate_GameEnded
	//	*GameUpdate_TileUpdate
	Update               isGameUpdate_Update `protobuf_oneof:"update"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GameUpdate) Reset()         { *m = GameUpdate{} }
func (m *GameUpdate) String() string { return proto.CompactTextString(m) }
func (*GameUpdate) ProtoMessage()    {}
func (*GameUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{9}
}

func (m *GameUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameUpdate.Unmarshal(m, b)
}
func (m *GameUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameUpdate.Marshal(b, m, deterministic)
}
func (m *GameUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameUpdate.Merge(m, src)
}
func (m *GameUpdate) XXX_Size() int {
	return xxx_messageInfo_GameUpdate.Size(m)
}
func (m *GameUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_GameUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_GameUpdate proto.InternalMessageInfo

type isGameUpdate_Update interface {
	isGameUpdate_Update()
}

type GameUpdate_CurrentStatus struct {
	CurrentStatus *CurrentStatus `protobuf:"bytes,1,opt,name=current_status,json=currentStatus,proto3,oneof"`
}

type GameUpdate_PlayerUpdate struct {
	PlayerUpdate *PlayerUpdate `protobuf:"bytes,2,opt,name=player_update,json=playerUpdate,proto3,oneof"`
}

type GameUpdate_GameStarted struct {
	GameStarted *GameStarted `protobuf:"bytes,3,opt,name=game_started,json=gameStarted,proto3,oneof"`
}

type GameUpdate_GameEnded struct {
	GameEnded *GameEnded `protobuf:"bytes,4,opt,name=game_ended,json=gameEnded,proto3,oneof"`
}

type GameUpdate_TileUpdate struct {
	TileUpdate *TileUpdate `protobuf:"bytes,5,opt,name=tile_update,json=tileUpdate,proto3,oneof"`
}

func (*GameUpdate_CurrentStatus) isGameUpdate_Update() {}

func (*GameUpdate_PlayerUpdate) isGameUpdate_Update() {}

func (*GameUpdate_GameStarted) isGameUpdate_Update() {}

func (*GameUpdate_GameEnded) isGameUpdate_Update() {}

func (*GameUpdate_TileUpdate) isGameUpdate_Update() {}

func (m *GameUpdate) GetUpdate() isGameUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *GameUpdate) GetCurrentStatus() *CurrentStatus {
	if x, ok := m.GetUpdate().(*GameUpdate_CurrentStatus); ok {
		return x.CurrentStatus
	}
	return nil
}

func (m *GameUpdate) GetPlayerUpdate() *PlayerUpdate {
	if x, ok := m.GetUpdate().(*GameUpdate_PlayerUpdate); ok {
		return x.PlayerUpdate
	}
	return nil
}

func (m *GameUpdate) GetGameStarted() *GameStarted {
	if x, ok := m.GetUpdate().(*GameUpdate_GameStarted); ok {
		return x.GameStarted
	}
	return nil
}

func (m *GameUpdate) GetGameEnded() *GameEnded {
	if x, ok := m.GetUpdate().(*GameUpdate_GameEnded); ok {
		return x.GameEnded
	}
	return nil
}

func (m *GameUpdate) GetTileUpdate() *TileUpdate {
	if x, ok := m.GetUpdate().(*GameUpdate_TileUpdate); ok {
		return x.TileUpdate
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GameUpdate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GameUpdate_CurrentStatus)(nil),
		(*GameUpdate_PlayerUpdate)(nil),
		(*GameUpdate_GameStarted)(nil),
		(*GameUpdate_GameEnded)(nil),
		(*GameUpdate_TileUpdate)(nil),
	}
}

type CurrentStatus struct {
	YourId               string     `protobuf:"bytes,1,opt,name=your_id,json=yourId,proto3" json:"your_id,omitempty"`
	Players              []*Player  `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	RemainingTiles       int32      `protobuf:"varint,3,opt,name=remaining_tiles,json=remainingTiles,proto3" json:"remaining_tiles,omitempty"`
	Board                *Board     `protobuf:"bytes,4,opt,name=board,proto3" json:"board,omitempty"`
	AllTiles             *Tiles     `protobuf:"bytes,5,opt,name=all_tiles,json=allTiles,proto3" json:"all_tiles,omitempty"`
	Status               GameStatus `protobuf:"varint,6,opt,name=status,proto3,enum=GameStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CurrentStatus) Reset()         { *m = CurrentStatus{} }
func (m *CurrentStatus) String() string { return proto.CompactTextString(m) }
func (*CurrentStatus) ProtoMessage()    {}
func (*CurrentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{10}
}

func (m *CurrentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentStatus.Unmarshal(m, b)
}
func (m *CurrentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentStatus.Marshal(b, m, deterministic)
}
func (m *CurrentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentStatus.Merge(m, src)
}
func (m *CurrentStatus) XXX_Size() int {
	return xxx_messageInfo_CurrentStatus.Size(m)
}
func (m *CurrentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentStatus proto.InternalMessageInfo

func (m *CurrentStatus) GetYourId() string {
	if m != nil {
		return m.YourId
	}
	return ""
}

func (m *CurrentStatus) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *CurrentStatus) GetRemainingTiles() int32 {
	if m != nil {
		return m.RemainingTiles
	}
	return 0
}

func (m *CurrentStatus) GetBoard() *Board {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *CurrentStatus) GetAllTiles() *Tiles {
	if m != nil {
		return m.AllTiles
	}
	return nil
}

func (m *CurrentStatus) GetStatus() GameStatus {
	if m != nil {
		return m.Status
	}
	return GameStatus_UNKNOWN
}

type Tiles struct {
	// Tiles are just lists of letters
	Letters              []string `protobuf:"bytes,1,rep,name=letters,proto3" json:"letters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tiles) Reset()         { *m = Tiles{} }
func (m *Tiles) String() string { return proto.CompactTextString(m) }
func (*Tiles) ProtoMessage()    {}
func (*Tiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{11}
}

func (m *Tiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tiles.Unmarshal(m, b)
}
func (m *Tiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tiles.Marshal(b, m, deterministic)
}
func (m *Tiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tiles.Merge(m, src)
}
func (m *Tiles) XXX_Size() int {
	return xxx_messageInfo_Tiles.Size(m)
}
func (m *Tiles) XXX_DiscardUnknown() {
	xxx_messageInfo_Tiles.DiscardUnknown(m)
}

var xxx_messageInfo_Tiles proto.InternalMessageInfo

func (m *Tiles) GetLetters() []string {
	if m != nil {
		return m.Letters
	}
	return nil
}

type PlayerUpdate struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	RemainingTiles       int32    `protobuf:"varint,2,opt,name=remaining_tiles,json=remainingTiles,proto3" json:"remaining_tiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerUpdate) Reset()         { *m = PlayerUpdate{} }
func (m *PlayerUpdate) String() string { return proto.CompactTextString(m) }
func (*PlayerUpdate) ProtoMessage()    {}
func (*PlayerUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{12}
}

func (m *PlayerUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerUpdate.Unmarshal(m, b)
}
func (m *PlayerUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerUpdate.Marshal(b, m, deterministic)
}
func (m *PlayerUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerUpdate.Merge(m, src)
}
func (m *PlayerUpdate) XXX_Size() int {
	return xxx_messageInfo_PlayerUpdate.Size(m)
}
func (m *PlayerUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerUpdate proto.InternalMessageInfo

func (m *PlayerUpdate) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerUpdate) GetRemainingTiles() int32 {
	if m != nil {
		return m.RemainingTiles
	}
	return 0
}

type Player struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TilesInHand          int32    `protobuf:"varint,3,opt,name=tiles_in_hand,json=tilesInHand,proto3" json:"tiles_in_hand,omitempty"`
	TilesInBoard         int32    `protobuf:"varint,4,opt,name=tiles_in_board,json=tilesInBoard,proto3" json:"tiles_in_board,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{13}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetTilesInHand() int32 {
	if m != nil {
		return m.TilesInHand
	}
	return 0
}

func (m *Player) GetTilesInBoard() int32 {
	if m != nil {
		return m.TilesInBoard
	}
	return 0
}

type GameStarted struct {
	NumStartingTiles     int32    `protobuf:"varint,1,opt,name=num_starting_tiles,json=numStartingTiles,proto3" json:"num_starting_tiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStarted) Reset()         { *m = GameStarted{} }
func (m *GameStarted) String() string { return proto.CompactTextString(m) }
func (*GameStarted) ProtoMessage()    {}
func (*GameStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{14}
}

func (m *GameStarted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStarted.Unmarshal(m, b)
}
func (m *GameStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStarted.Marshal(b, m, deterministic)
}
func (m *GameStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStarted.Merge(m, src)
}
func (m *GameStarted) XXX_Size() int {
	return xxx_messageInfo_GameStarted.Size(m)
}
func (m *GameStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStarted.DiscardUnknown(m)
}

var xxx_messageInfo_GameStarted proto.InternalMessageInfo

func (m *GameStarted) GetNumStartingTiles() int32 {
	if m != nil {
		return m.NumStartingTiles
	}
	return 0
}

type GameEnded struct {
	Standings            []*Player `protobuf:"bytes,1,rep,name=standings,proto3" json:"standings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameEnded) Reset()         { *m = GameEnded{} }
func (m *GameEnded) String() string { return proto.CompactTextString(m) }
func (*GameEnded) ProtoMessage()    {}
func (*GameEnded) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{15}
}

func (m *GameEnded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEnded.Unmarshal(m, b)
}
func (m *GameEnded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEnded.Marshal(b, m, deterministic)
}
func (m *GameEnded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEnded.Merge(m, src)
}
func (m *GameEnded) XXX_Size() int {
	return xxx_messageInfo_GameEnded.Size(m)
}
func (m *GameEnded) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEnded.DiscardUnknown(m)
}

var xxx_messageInfo_GameEnded proto.InternalMessageInfo

func (m *GameEnded) GetStandings() []*Player {
	if m != nil {
		return m.Standings
	}
	return nil
}

type TileUpdate struct {
	AllTiles             *Tiles   `protobuf:"bytes,1,opt,name=all_tiles,json=allTiles,proto3" json:"all_tiles,omitempty"`
	FromOtherPeel        bool     `protobuf:"varint,2,opt,name=from_other_peel,json=fromOtherPeel,proto3" json:"from_other_peel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileUpdate) Reset()         { *m = TileUpdate{} }
func (m *TileUpdate) String() string { return proto.CompactTextString(m) }
func (*TileUpdate) ProtoMessage()    {}
func (*TileUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{16}
}

func (m *TileUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileUpdate.Unmarshal(m, b)
}
func (m *TileUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileUpdate.Marshal(b, m, deterministic)
}
func (m *TileUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileUpdate.Merge(m, src)
}
func (m *TileUpdate) XXX_Size() int {
	return xxx_messageInfo_TileUpdate.Size(m)
}
func (m *TileUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TileUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TileUpdate proto.InternalMessageInfo

func (m *TileUpdate) GetAllTiles() *Tiles {
	if m != nil {
		return m.AllTiles
	}
	return nil
}

func (m *TileUpdate) GetFromOtherPeel() bool {
	if m != nil {
		return m.FromOtherPeel
	}
	return false
}

type StreamLogsRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamLogsRequest) Reset()         { *m = StreamLogsRequest{} }
func (m *StreamLogsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamLogsRequest) ProtoMessage()    {}
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{17}
}

func (m *StreamLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamLogsRequest.Unmarshal(m, b)
}
func (m *StreamLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamLogsRequest.Marshal(b, m, deterministic)
}
func (m *StreamLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamLogsRequest.Merge(m, src)
}
func (m *StreamLogsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamLogsRequest.Size(m)
}
func (m *StreamLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamLogsRequest proto.InternalMessageInfo

func (m *StreamLogsRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *StreamLogsRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type LogEntry struct {
	// Types that are valid to be assigned to LogEvent:
	//	*LogEntry_PlayerMove
	//	*LogEntry_PlayerDump
	//	*LogEntry_WordFail
	LogEvent             isLogEntry_LogEvent `protobuf_oneof:"log_event"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{18}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

type isLogEntry_LogEvent interface {
	isLogEntry_LogEvent()
}

type LogEntry_PlayerMove struct {
	PlayerMove *PlayerMove `protobuf:"bytes,1,opt,name=player_move,json=playerMove,proto3,oneof"`
}

type LogEntry_PlayerDump struct {
	PlayerDump *PlayerDump `protobuf:"bytes,2,opt,name=player_dump,json=playerDump,proto3,oneof"`
}

type LogEntry_WordFail struct {
	WordFail *WordFail `protobuf:"bytes,3,opt,name=word_fail,json=wordFail,proto3,oneof"`
}

func (*LogEntry_PlayerMove) isLogEntry_LogEvent() {}

func (*LogEntry_PlayerDump) isLogEntry_LogEvent() {}

func (*LogEntry_WordFail) isLogEntry_LogEvent() {}

func (m *LogEntry) GetLogEvent() isLogEntry_LogEvent {
	if m != nil {
		return m.LogEvent
	}
	return nil
}

func (m *LogEntry) GetPlayerMove() *PlayerMove {
	if x, ok := m.GetLogEvent().(*LogEntry_PlayerMove); ok {
		return x.PlayerMove
	}
	return nil
}

func (m *LogEntry) GetPlayerDump() *PlayerDump {
	if x, ok := m.GetLogEvent().(*LogEntry_PlayerDump); ok {
		return x.PlayerDump
	}
	return nil
}

func (m *LogEntry) GetWordFail() *WordFail {
	if x, ok := m.GetLogEvent().(*LogEntry_WordFail); ok {
		return x.WordFail
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LogEntry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LogEntry_PlayerMove)(nil),
		(*LogEntry_PlayerDump)(nil),
		(*LogEntry_WordFail)(nil),
	}
}

type PlayerMove struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Word                 string   `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMove) Reset()         { *m = PlayerMove{} }
func (m *PlayerMove) String() string { return proto.CompactTextString(m) }
func (*PlayerMove) ProtoMessage()    {}
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{19}
}

func (m *PlayerMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMove.Unmarshal(m, b)
}
func (m *PlayerMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMove.Marshal(b, m, deterministic)
}
func (m *PlayerMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMove.Merge(m, src)
}
func (m *PlayerMove) XXX_Size() int {
	return xxx_messageInfo_PlayerMove.Size(m)
}
func (m *PlayerMove) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMove.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMove proto.InternalMessageInfo

func (m *PlayerMove) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerMove) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerMove) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

type PlayerDump struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDump) Reset()         { *m = PlayerDump{} }
func (m *PlayerDump) String() string { return proto.CompactTextString(m) }
func (*PlayerDump) ProtoMessage()    {}
func (*PlayerDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{20}
}

func (m *PlayerDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDump.Unmarshal(m, b)
}
func (m *PlayerDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDump.Marshal(b, m, deterministic)
}
func (m *PlayerDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDump.Merge(m, src)
}
func (m *PlayerDump) XXX_Size() int {
	return xxx_messageInfo_PlayerDump.Size(m)
}
func (m *PlayerDump) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDump.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDump proto.InternalMessageInfo

func (m *PlayerDump) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerDump) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type WordFail struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	BadWord              string   `protobuf:"bytes,3,opt,name=bad_word,json=badWord,proto3" json:"bad_word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordFail) Reset()         { *m = WordFail{} }
func (m *WordFail) String() string { return proto.CompactTextString(m) }
func (*WordFail) ProtoMessage()    {}
func (*WordFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{21}
}

func (m *WordFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordFail.Unmarshal(m, b)
}
func (m *WordFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordFail.Marshal(b, m, deterministic)
}
func (m *WordFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordFail.Merge(m, src)
}
func (m *WordFail) XXX_Size() int {
	return xxx_messageInfo_WordFail.Size(m)
}
func (m *WordFail) XXX_DiscardUnknown() {
	xxx_messageInfo_WordFail.DiscardUnknown(m)
}

var xxx_messageInfo_WordFail proto.InternalMessageInfo

func (m *WordFail) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *WordFail) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *WordFail) GetBadWord() string {
	if m != nil {
		return m.BadWord
	}
	return ""
}

type SpectateRequest struct {
	// The unique identifier for the game to spectate.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpectateRequest) Reset()         { *m = SpectateRequest{} }
func (m *SpectateRequest) String() string { return proto.CompactTextString(m) }
func (*SpectateRequest) ProtoMessage()    {}
func (*SpectateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{22}
}

func (m *SpectateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpectateRequest.Unmarshal(m, b)
}
func (m *SpectateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpectateRequest.Marshal(b, m, deterministic)
}
func (m *SpectateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpectateRequest.Merge(m, src)
}
func (m *SpectateRequest) XXX_Size() int {
	return xxx_messageInfo_SpectateRequest.Size(m)
}
func (m *SpectateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpectateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpectateRequest proto.InternalMessageInfo

func (m *SpectateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SpectateUpdate struct {
	PlayerId             string      `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName           string      `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Board                *Board      `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	InvalidWords         []*CharLocs `protobuf:"bytes,4,rep,name=invalid_words,json=invalidWords,proto3" json:"invalid_words,omitempty"`
	DetachedBoard        bool        `protobuf:"varint,5,opt,name=detached_board,json=detachedBoard,proto3" json:"detached_board,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SpectateUpdate) Reset()         { *m = SpectateUpdate{} }
func (m *SpectateUpdate) String() string { return proto.CompactTextString(m) }
func (*SpectateUpdate) ProtoMessage()    {}
func (*SpectateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{23}
}

func (m *SpectateUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpectateUpdate.Unmarshal(m, b)
}
func (m *SpectateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpectateUpdate.Marshal(b, m, deterministic)
}
func (m *SpectateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpectateUpdate.Merge(m, src)
}
func (m *SpectateUpdate) XXX_Size() int {
	return xxx_messageInfo_SpectateUpdate.Size(m)
}
func (m *SpectateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_SpectateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_SpectateUpdate proto.InternalMessageInfo

func (m *SpectateUpdate) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *SpectateUpdate) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *SpectateUpdate) GetBoard() *Board {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *SpectateUpdate) GetInvalidWords() []*CharLocs {
	if m != nil {
		return m.InvalidWords
	}
	return nil
}

func (m *SpectateUpdate) GetDetachedBoard() bool {
	if m != nil {
		return m.DetachedBoard
	}
	return false
}

type DumpRequest struct {
	// The unique identifier for the game you're dumping in.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The unique identifier for the player dumping.
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// The letter that is being dumped.
	Letter               string   `protobuf:"bytes,3,opt,name=letter,proto3" json:"letter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpRequest) Reset()         { *m = DumpRequest{} }
func (m *DumpRequest) String() string { return proto.CompactTextString(m) }
func (*DumpRequest) ProtoMessage()    {}
func (*DumpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{24}
}

func (m *DumpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpRequest.Unmarshal(m, b)
}
func (m *DumpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpRequest.Marshal(b, m, deterministic)
}
func (m *DumpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpRequest.Merge(m, src)
}
func (m *DumpRequest) XXX_Size() int {
	return xxx_messageInfo_DumpRequest.Size(m)
}
func (m *DumpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpRequest proto.InternalMessageInfo

func (m *DumpRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DumpRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *DumpRequest) GetLetter() string {
	if m != nil {
		return m.Letter
	}
	return ""
}

type DumpResponse struct {
	AllTiles             *Tiles   `protobuf:"bytes,1,opt,name=all_tiles,json=allTiles,proto3" json:"all_tiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpResponse) Reset()         { *m = DumpResponse{} }
func (m *DumpResponse) String() string { return proto.CompactTextString(m) }
func (*DumpResponse) ProtoMessage()    {}
func (*DumpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{25}
}

func (m *DumpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpResponse.Unmarshal(m, b)
}
func (m *DumpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpResponse.Marshal(b, m, deterministic)
}
func (m *DumpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpResponse.Merge(m, src)
}
func (m *DumpResponse) XXX_Size() int {
	return xxx_messageInfo_DumpResponse.Size(m)
}
func (m *DumpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpResponse proto.InternalMessageInfo

func (m *DumpResponse) GetAllTiles() *Tiles {
	if m != nil {
		return m.AllTiles
	}
	return nil
}

type UpdateBoardRequest struct {
	// The unique identifier for the game you're placing in.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The unique identifier for the player peeling.
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Board    *Board `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	// An optional word to include, to be shared with other players.
	LatestWord           *Word    `protobuf:"bytes,4,opt,name=latest_word,json=latestWord,proto3" json:"latest_word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBoardRequest) Reset()         { *m = UpdateBoardRequest{} }
func (m *UpdateBoardRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBoardRequest) ProtoMessage()    {}
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{26}
}

func (m *UpdateBoardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBoardRequest.Unmarshal(m, b)
}
func (m *UpdateBoardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBoardRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBoardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBoardRequest.Merge(m, src)
}
func (m *UpdateBoardRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBoardRequest.Size(m)
}
func (m *UpdateBoardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBoardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBoardRequest proto.InternalMessageInfo

func (m *UpdateBoardRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateBoardRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *UpdateBoardRequest) GetBoard() *Board {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *UpdateBoardRequest) GetLatestWord() *Word {
	if m != nil {
		return m.LatestWord
	}
	return nil
}

type Board struct {
	Words                []*Word  `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Board) Reset()         { *m = Board{} }
func (m *Board) String() string { return proto.CompactTextString(m) }
func (*Board) ProtoMessage()    {}
func (*Board) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{27}
}

func (m *Board) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Board.Unmarshal(m, b)
}
func (m *Board) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Board.Marshal(b, m, deterministic)
}
func (m *Board) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Board.Merge(m, src)
}
func (m *Board) XXX_Size() int {
	return xxx_messageInfo_Board.Size(m)
}
func (m *Board) XXX_DiscardUnknown() {
	xxx_messageInfo_Board.DiscardUnknown(m)
}

var xxx_messageInfo_Board proto.InternalMessageInfo

func (m *Board) GetWords() []*Word {
	if m != nil {
		return m.Words
	}
	return nil
}

type Word struct {
	Text        string           `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Orientation Word_Orientation `protobuf:"varint,2,opt,name=orientation,proto3,enum=Word_Orientation" json:"orientation,omitempty"`
	// The x-position of the top-left letter on the board.
	X int32 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	// The y-position of the top-left letter on the board.
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{28}
}

func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (m *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(m, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Word) GetOrientation() Word_Orientation {
	if m != nil {
		return m.Orientation
	}
	return Word_UNKNOWN
}

func (m *Word) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Word) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type CharLocs struct {
	Text                 string     `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Locs                 []*CharLoc `protobuf:"bytes,2,rep,name=locs,proto3" json:"locs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CharLocs) Reset()         { *m = CharLocs{} }
func (m *CharLocs) String() string { return proto.CompactTextString(m) }
func (*CharLocs) ProtoMessage()    {}
func (*CharLocs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{29}
}

func (m *CharLocs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharLocs.Unmarshal(m, b)
}
func (m *CharLocs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharLocs.Marshal(b, m, deterministic)
}
func (m *CharLocs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharLocs.Merge(m, src)
}
func (m *CharLocs) XXX_Size() int {
	return xxx_messageInfo_CharLocs.Size(m)
}
func (m *CharLocs) XXX_DiscardUnknown() {
	xxx_messageInfo_CharLocs.DiscardUnknown(m)
}

var xxx_messageInfo_CharLocs proto.InternalMessageInfo

func (m *CharLocs) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CharLocs) GetLocs() []*CharLoc {
	if m != nil {
		return m.Locs
	}
	return nil
}

type CharLoc struct {
	Letter               string   `protobuf:"bytes,1,opt,name=letter,proto3" json:"letter,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharLoc) Reset()         { *m = CharLoc{} }
func (m *CharLoc) String() string { return proto.CompactTextString(m) }
func (*CharLoc) ProtoMessage()    {}
func (*CharLoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{30}
}

func (m *CharLoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharLoc.Unmarshal(m, b)
}
func (m *CharLoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharLoc.Marshal(b, m, deterministic)
}
func (m *CharLoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharLoc.Merge(m, src)
}
func (m *CharLoc) XXX_Size() int {
	return xxx_messageInfo_CharLoc.Size(m)
}
func (m *CharLoc) XXX_DiscardUnknown() {
	xxx_messageInfo_CharLoc.DiscardUnknown(m)
}

var xxx_messageInfo_CharLoc proto.InternalMessageInfo

func (m *CharLoc) GetLetter() string {
	if m != nil {
		return m.Letter
	}
	return ""
}

func (m *CharLoc) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CharLoc) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type UpdateBoardResponse struct {
	InvalidWords         []*CharLocs `protobuf:"bytes,1,rep,name=invalid_words,json=invalidWords,proto3" json:"invalid_words,omitempty"`
	UnusedLetters        []string    `protobuf:"bytes,2,rep,name=unused_letters,json=unusedLetters,proto3" json:"unused_letters,omitempty"`
	DetachedBoard        bool        `protobuf:"varint,3,opt,name=detached_board,json=detachedBoard,proto3" json:"detached_board,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateBoardResponse) Reset()         { *m = UpdateBoardResponse{} }
func (m *UpdateBoardResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBoardResponse) ProtoMessage()    {}
func (*UpdateBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022f69d17e210ba, []int{31}
}

func (m *UpdateBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBoardResponse.Unmarshal(m, b)
}
func (m *UpdateBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBoardResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBoardResponse.Merge(m, src)
}
func (m *UpdateBoardResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBoardResponse.Size(m)
}
func (m *UpdateBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBoardResponse proto.InternalMessageInfo

func (m *UpdateBoardResponse) GetInvalidWords() []*CharLocs {
	if m != nil {
		return m.InvalidWords
	}
	return nil
}

func (m *UpdateBoardResponse) GetUnusedLetters() []string {
	if m != nil {
		return m.UnusedLetters
	}
	return nil
}

func (m *UpdateBoardResponse) GetDetachedBoard() bool {
	if m != nil {
		return m.DetachedBoard
	}
	return false
}

func init() {
	proto.RegisterEnum("GameStatus", GameStatus_name, GameStatus_value)
	proto.RegisterEnum("Word_Orientation", Word_Orientation_name, Word_Orientation_value)
	proto.RegisterType((*NewGameRequest)(nil), "NewGameRequest")
	proto.RegisterType((*NewGameResponse)(nil), "NewGameResponse")
	proto.RegisterType((*ListGamesRequest)(nil), "ListGamesRequest")
	proto.RegisterType((*ListGamesResponse)(nil), "ListGamesResponse")
	proto.RegisterType((*GamesList)(nil), "GamesList")
	proto.RegisterType((*Game)(nil), "Game")
	proto.RegisterType((*StartGameRequest)(nil), "StartGameRequest")
	proto.RegisterType((*StartGameResponse)(nil), "StartGameResponse")
	proto.RegisterType((*JoinGameRequest)(nil), "JoinGameRequest")
	proto.RegisterType((*GameUpdate)(nil), "GameUpdate")
	proto.RegisterType((*CurrentStatus)(nil), "CurrentStatus")
	proto.RegisterType((*Tiles)(nil), "Tiles")
	proto.RegisterType((*PlayerUpdate)(nil), "PlayerUpdate")
	proto.RegisterType((*Player)(nil), "Player")
	proto.RegisterType((*GameStarted)(nil), "GameStarted")
	proto.RegisterType((*GameEnded)(nil), "GameEnded")
	proto.RegisterType((*TileUpdate)(nil), "TileUpdate")
	proto.RegisterType((*StreamLogsRequest)(nil), "StreamLogsRequest")
	proto.RegisterType((*LogEntry)(nil), "LogEntry")
	proto.RegisterType((*PlayerMove)(nil), "PlayerMove")
	proto.RegisterType((*PlayerDump)(nil), "PlayerDump")
	proto.RegisterType((*WordFail)(nil), "WordFail")
	proto.RegisterType((*SpectateRequest)(nil), "SpectateRequest")
	proto.RegisterType((*SpectateUpdate)(nil), "SpectateUpdate")
	proto.RegisterType((*DumpRequest)(nil), "DumpRequest")
	proto.RegisterType((*DumpResponse)(nil), "DumpResponse")
	proto.RegisterType((*UpdateBoardRequest)(nil), "UpdateBoardRequest")
	proto.RegisterType((*Board)(nil), "Board")
	proto.RegisterType((*Word)(nil), "Word")
	proto.RegisterType((*CharLocs)(nil), "CharLocs")
	proto.RegisterType((*CharLoc)(nil), "CharLoc")
	proto.RegisterType((*UpdateBoardResponse)(nil), "UpdateBoardResponse")
}

func init() { proto.RegisterFile("banana.proto", fileDescriptor_0022f69d17e210ba) }

var fileDescriptor_0022f69d17e210ba = []byte{
	// 1377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x75, 0xe6, 0x50, 0x27, 0xaf, 0x7f, 0xfc, 0x51, 0x95, 0x00, 0xb1, 0x99, 0x43, 0x8d,
	0x26, 0xdd, 0xba, 0x4a, 0x81, 0x06, 0x68, 0x7b, 0x61, 0x3b, 0x4e, 0xa4, 0x54, 0x95, 0xdc, 0x95,
	0xd3, 0x34, 0xb9, 0x28, 0xb1, 0x16, 0x37, 0x32, 0x01, 0x8a, 0x54, 0xc9, 0x95, 0x13, 0x3f, 0x41,
	0x1f, 0xa0, 0xe8, 0x03, 0xf4, 0xa2, 0x0f, 0x52, 0xf4, 0x35, 0xfa, 0x30, 0xc5, 0x1e, 0x48, 0x51,
	0xb2, 0xec, 0x06, 0xcd, 0x9d, 0x66, 0x38, 0x3b, 0xfb, 0xcd, 0xec, 0x37, 0x07, 0x41, 0xf5, 0x94,
	0x06, 0x34, 0xa0, 0x78, 0x16, 0x85, 0x3c, 0xb4, 0xef, 0x42, 0x7d, 0xc0, 0xde, 0x3e, 0xa3, 0x53,
	0x46, 0xd8, 0xcf, 0x73, 0x16, 0x73, 0x84, 0xa0, 0x10, 0xd0, 0x29, 0x6b, 0x19, 0xdb, 0xc6, 0xae,
	0x49, 0xe4, 0x6f, 0x7b, 0x07, 0x1a, 0xa9, 0x55, 0x3c, 0x0b, 0x83, 0x98, 0xa1, 0x3a, 0xe4, 0x3c,
	0x57, 0x1b, 0xe5, 0x3c, 0xd7, 0x46, 0xd0, 0xec, 0x7b, 0x31, 0x17, 0x36, 0xb1, 0x76, 0x65, 0xef,
	0xc1, 0x66, 0x46, 0xa7, 0x0f, 0xde, 0x84, 0xe2, 0x44, 0x28, 0x5a, 0xc6, 0x76, 0x7e, 0xd7, 0xea,
	0x14, 0xb1, 0x74, 0xab, 0x74, 0xf6, 0x2e, 0x98, 0xd2, 0x5a, 0x1c, 0xbb, 0xde, 0x32, 0x82, 0x82,
	0x10, 0x57, 0x71, 0xa4, 0xf0, 0x73, 0x0b, 0xf8, 0xe8, 0x0e, 0x94, 0x62, 0x4e, 0xf9, 0x3c, 0x6e,
	0xe5, 0xb7, 0x8d, 0xdd, 0x7a, 0xc7, 0x92, 0x9e, 0x46, 0x52, 0x45, 0xf4, 0x27, 0xb4, 0x03, 0xd5,
	0x99, 0x4f, 0x2f, 0x58, 0xe4, 0x8c, 0xc3, 0x79, 0xc0, 0x5b, 0x85, 0x6d, 0x63, 0xb7, 0x48, 0x2c,
	0xa5, 0x3b, 0x14, 0x2a, 0xdb, 0x86, 0xe6, 0x88, 0xd3, 0x88, 0x67, 0xd3, 0xb5, 0x9a, 0x87, 0x2d,
	0xd8, 0xcc, 0xd8, 0xa8, 0x98, 0x6d, 0x02, 0x8d, 0xe7, 0xa1, 0x17, 0x5c, 0x73, 0x6e, 0x2d, 0xee,
	0x9b, 0x60, 0x6a, 0x48, 0x9e, 0x2b, 0xa1, 0x9b, 0xa4, 0xa2, 0x14, 0x3d, 0xd7, 0xfe, 0x2d, 0x07,
	0x20, 0x1c, 0xbe, 0x98, 0xb9, 0x94, 0x33, 0xf4, 0x25, 0xd4, 0xc7, 0xf3, 0x28, 0x62, 0x01, 0x77,
	0x74, 0xac, 0xc2, 0xb7, 0xd5, 0xa9, 0xe3, 0x43, 0xa5, 0x56, 0xe1, 0x76, 0x37, 0x48, 0x6d, 0x9c,
	0x55, 0xa0, 0x2f, 0xa0, 0xa6, 0x2f, 0x99, 0x4b, 0x4f, 0x12, 0x81, 0xd5, 0xa9, 0xe1, 0x63, 0xa9,
	0x55, 0xee, 0xbb, 0x1b, 0x44, 0x67, 0x47, 0x5f, 0xf7, 0x39, 0x54, 0xc5, 0x3b, 0x88, 0xbb, 0x22,
	0xce, 0x14, 0x3a, 0xab, 0x53, 0x4d, 0x12, 0x2b, 0x74, 0xdd, 0x0d, 0x62, 0x4d, 0x16, 0x22, 0x7a,
	0x00, 0x20, 0x8f, 0xb0, 0xc0, 0x65, 0xae, 0x4c, 0xaf, 0xd5, 0x01, 0x79, 0xe0, 0x48, 0x68, 0xba,
	0x1b, 0xc4, 0x9c, 0x24, 0x02, 0xc2, 0x60, 0x71, 0xcf, 0x67, 0x09, 0xa6, 0xa2, 0xb4, 0xb6, 0xf0,
	0x89, 0xe7, 0xb3, 0x14, 0x11, 0xf0, 0x54, 0x3a, 0xa8, 0x40, 0x49, 0x99, 0xda, 0x7f, 0x1b, 0x50,
	0x5b, 0x0a, 0x19, 0xdd, 0x80, 0xf2, 0x45, 0x38, 0x97, 0x49, 0x54, 0xf9, 0x2e, 0x09, 0xb1, 0xe7,
	0xa2, 0x1d, 0x28, 0xab, 0xa0, 0xe2, 0x56, 0x4e, 0x52, 0xac, 0xac, 0x83, 0x26, 0x89, 0x1e, 0x7d,
	0x0c, 0x8d, 0x88, 0x4d, 0xa9, 0x17, 0x78, 0xc1, 0xc4, 0x11, 0xf7, 0x29, 0x0e, 0x15, 0x49, 0x3d,
	0x55, 0x0b, 0x4c, 0x31, 0xba, 0x05, 0xc5, 0xd3, 0x90, 0x46, 0x49, 0x60, 0x25, 0x7c, 0x20, 0x24,
	0xa2, 0x94, 0xe8, 0x0e, 0x98, 0xd4, 0xf7, 0xb5, 0x83, 0xa2, 0xb6, 0x90, 0x07, 0x49, 0x85, 0xfa,
	0xbe, 0x72, 0xb1, 0xa0, 0x69, 0xe9, 0x4a, 0x9a, 0xda, 0x3b, 0x50, 0x54, 0xd6, 0x2d, 0x28, 0xfb,
	0x8c, 0x73, 0x01, 0x5e, 0xd4, 0x87, 0x49, 0x12, 0xd1, 0xfe, 0x11, 0xaa, 0xd9, 0xb7, 0x43, 0xb7,
	0xa1, 0xa4, 0xc2, 0xd1, 0x94, 0x48, 0xa3, 0xd4, 0xea, 0x75, 0x41, 0xe6, 0xd6, 0x05, 0x69, 0x9f,
	0x43, 0x49, 0x1d, 0x7d, 0x2f, 0xfa, 0xda, 0x50, 0x93, 0xce, 0x1c, 0x2f, 0x70, 0xce, 0x68, 0xe0,
	0xea, 0xcc, 0xc9, 0x87, 0x8d, 0x7b, 0x41, 0x97, 0x06, 0x2e, 0xba, 0x0b, 0xf5, 0xd4, 0x66, 0x91,
	0xbf, 0x22, 0xa9, 0x6a, 0x23, 0x99, 0x45, 0xfb, 0x2b, 0xb0, 0x32, 0xc4, 0x42, 0x0f, 0x01, 0x05,
	0xf3, 0xa9, 0xe2, 0xde, 0x02, 0xb2, 0x21, 0x0f, 0x36, 0x83, 0xf9, 0x74, 0xa4, 0x3f, 0x28, 0xd0,
	0x1d, 0xd5, 0x53, 0x14, 0xaf, 0xee, 0x81, 0x19, 0x73, 0x1a, 0xb8, 0x5e, 0x30, 0x49, 0xfa, 0x4a,
	0x9a, 0x8e, 0xc5, 0x17, 0xfb, 0x15, 0xc0, 0x82, 0x6a, 0xcb, 0xaf, 0x67, 0x5c, 0xf1, 0x7a, 0xf7,
	0xa1, 0xf1, 0x26, 0x0a, 0xa7, 0x4e, 0xc8, 0xcf, 0x58, 0xe4, 0xcc, 0x18, 0xf3, 0x65, 0x32, 0x2a,
	0xa4, 0x26, 0xd4, 0x43, 0xa1, 0x3d, 0x66, 0xcc, 0xb7, 0x7b, 0xa2, 0x41, 0x44, 0x8c, 0x4e, 0xfb,
	0xe1, 0x24, 0xe9, 0x94, 0x82, 0xa2, 0xb2, 0x36, 0x16, 0x14, 0x15, 0x62, 0xcf, 0x5d, 0x6e, 0x01,
	0xb9, 0x95, 0x16, 0xf0, 0xbb, 0x01, 0x95, 0x7e, 0x38, 0x39, 0x0a, 0x78, 0x74, 0x21, 0x2a, 0x46,
	0x5b, 0x4e, 0xc3, 0x73, 0xa6, 0x61, 0x5a, 0x3a, 0xb6, 0xef, 0xc2, 0x73, 0x59, 0x31, 0xb3, 0x54,
	0xca, 0xd8, 0xbb, 0xf3, 0xe9, 0x4c, 0x57, 0x7d, 0x62, 0xff, 0x64, 0x3e, 0x9d, 0x2d, 0xec, 0x85,
	0x84, 0x76, 0xc1, 0x7c, 0x1b, 0x46, 0xae, 0xf3, 0x86, 0x7a, 0xbe, 0x2e, 0x77, 0x13, 0xbf, 0x0c,
	0x23, 0xf7, 0x29, 0xf5, 0xfc, 0xee, 0x06, 0xa9, 0xbc, 0xd5, 0xbf, 0x0f, 0x2c, 0x30, 0xfd, 0x70,
	0xe2, 0xb0, 0x73, 0x16, 0x70, 0xfb, 0x27, 0x80, 0x05, 0x84, 0xe5, 0x70, 0x8c, 0xe5, 0x70, 0xd0,
	0xed, 0x14, 0x51, 0x86, 0x4a, 0x1a, 0xc2, 0x40, 0x10, 0x0a, 0x41, 0x41, 0x5c, 0xa2, 0x5b, 0xa1,
	0xfc, 0x6d, 0x3f, 0x4f, 0xfc, 0x4b, 0x90, 0x1f, 0xe4, 0xdf, 0x1e, 0x43, 0x25, 0x09, 0xe8, 0x03,
	0x91, 0x7e, 0x04, 0x95, 0x53, 0xea, 0x3a, 0x19, 0xb4, 0xe5, 0x53, 0xea, 0x0a, 0xe7, 0x62, 0x96,
	0x8e, 0x66, 0x6c, 0xcc, 0x29, 0xbf, 0x72, 0x86, 0xfc, 0x65, 0x40, 0x3d, 0xb1, 0xd1, 0x14, 0xfc,
	0x30, 0x38, 0x69, 0x73, 0xca, 0xaf, 0x6b, 0x4e, 0x18, 0x6a, 0x5e, 0x70, 0x4e, 0x7d, 0x4f, 0x01,
	0x8e, 0x5b, 0x05, 0x59, 0x17, 0x26, 0x3e, 0x3c, 0xa3, 0x51, 0x3f, 0x1c, 0xc7, 0xa4, 0xaa, 0xbf,
	0x8b, 0x00, 0x62, 0x74, 0x0f, 0xea, 0x2e, 0xe3, 0x74, 0x7c, 0xc6, 0x5c, 0x5d, 0xb3, 0x45, 0x45,
	0xf4, 0x44, 0xab, 0x8a, 0x96, 0x80, 0x25, 0xde, 0xe4, 0xaa, 0x81, 0x77, 0x1d, 0xb3, 0xd1, 0xff,
	0xa1, 0xa4, 0xba, 0x99, 0xce, 0x9e, 0x96, 0xec, 0x47, 0x50, 0x55, 0x3e, 0xf5, 0x32, 0xf1, 0x3e,
	0x95, 0x69, 0xff, 0x62, 0x00, 0xd2, 0x63, 0x42, 0x86, 0xfd, 0x5f, 0x00, 0x5d, 0x9f, 0xc1, 0xfb,
	0x60, 0xf9, 0x94, 0xb3, 0x98, 0xab, 0x17, 0x57, 0x23, 0xa0, 0x28, 0xab, 0x83, 0x80, 0xfa, 0x22,
	0xdf, 0xfe, 0x2e, 0x14, 0xe5, 0x39, 0xb1, 0xda, 0xa8, 0x54, 0x27, 0xab, 0x8d, 0x34, 0x55, 0x3a,
	0xfb, 0x0f, 0x03, 0x0a, 0x42, 0x16, 0x7c, 0xe7, 0xec, 0x1d, 0x4f, 0x56, 0x31, 0xf1, 0x1b, 0x3d,
	0x02, 0x2b, 0x8c, 0x3c, 0x16, 0x70, 0xca, 0xbd, 0x30, 0x90, 0x38, 0xeb, 0x9d, 0x4d, 0x79, 0x1e,
	0x0f, 0x17, 0x1f, 0x48, 0xd6, 0x0a, 0x55, 0xc1, 0x78, 0xa7, 0xbb, 0xaf, 0xf1, 0x4e, 0x48, 0x17,
	0xba, 0xcd, 0x1a, 0x17, 0xf6, 0x63, 0xb0, 0x32, 0xe7, 0x90, 0x05, 0xe5, 0x17, 0x83, 0x6f, 0x07,
	0xc3, 0x97, 0x83, 0xe6, 0x06, 0xaa, 0x03, 0x74, 0x87, 0xa4, 0xf7, 0x7a, 0x38, 0x38, 0xd9, 0xef,
	0x37, 0x0d, 0x54, 0x85, 0xca, 0x0f, 0x47, 0xe4, 0xa4, 0x77, 0xb8, 0xdf, 0x6f, 0xe6, 0xec, 0xaf,
	0xa1, 0x92, 0x30, 0x64, 0x2d, 0xd4, 0x5b, 0x50, 0xf0, 0xc3, 0x71, 0x32, 0x5b, 0x2b, 0x09, 0x9d,
	0x88, 0xd4, 0xda, 0xdf, 0x40, 0x59, 0x2b, 0x32, 0xaf, 0x6d, 0x64, 0x5f, 0x5b, 0xc1, 0xce, 0x2d,
	0xc1, 0xce, 0x27, 0xb0, 0x7f, 0x35, 0x60, 0x6b, 0xe9, 0x51, 0x35, 0x23, 0x2e, 0x91, 0xd9, 0xf8,
	0x57, 0x32, 0xcf, 0x83, 0x79, 0xcc, 0x5c, 0x27, 0x99, 0xa6, 0x39, 0x39, 0x4d, 0x6b, 0x4a, 0xdb,
	0x57, 0xca, 0x35, 0x9c, 0xcf, 0xaf, 0xe1, 0xfc, 0x27, 0xdf, 0xab, 0x9d, 0x4c, 0x2f, 0x1e, 0x4b,
	0xb9, 0xbc, 0x01, 0x5b, 0x2f, 0xf7, 0x7b, 0x27, 0xbd, 0xc1, 0x33, 0xe7, 0xe9, 0x90, 0x38, 0xc7,
	0xfd, 0xfd, 0x57, 0x47, 0x64, 0xd4, 0x34, 0x50, 0x03, 0xac, 0xde, 0xc0, 0x39, 0x26, 0xc3, 0x67,
	0xe4, 0x68, 0x34, 0x6a, 0xe6, 0x44, 0x96, 0x9f, 0xf6, 0x06, 0xbd, 0x51, 0xf7, 0xe8, 0x49, 0x33,
	0xdf, 0xf9, 0x33, 0x0f, 0xb5, 0x03, 0xb9, 0xb2, 0x8f, 0x58, 0x74, 0xee, 0x8d, 0x19, 0x7a, 0x08,
	0x65, 0xbd, 0x8d, 0xa3, 0x06, 0x5e, 0xde, 0xde, 0xdb, 0x4d, 0xbc, 0xba, 0xa8, 0x77, 0xc0, 0x4c,
	0x97, 0x70, 0xb4, 0x89, 0x57, 0x97, 0xf4, 0x36, 0xc2, 0x97, 0x77, 0x74, 0x0c, 0x96, 0x9a, 0x51,
	0x57, 0x9e, 0x52, 0x8b, 0x9b, 0xdc, 0xd3, 0xf7, 0x0c, 0x71, 0x47, 0xba, 0xf4, 0xa2, 0x4d, 0xbc,
	0xba, 0x24, 0xb7, 0x11, 0xbe, 0xb4, 0x13, 0xa3, 0x07, 0x50, 0x49, 0x76, 0x62, 0xd4, 0xc4, 0x2b,
	0xeb, 0x71, 0x5b, 0xed, 0x3e, 0xea, 0x81, 0xf7, 0x0c, 0xf4, 0x29, 0xc0, 0x62, 0x68, 0x22, 0xe1,
	0x6e, 0x65, 0x82, 0xb6, 0x4d, 0x9c, 0x4c, 0xc2, 0x3d, 0x03, 0x3d, 0x06, 0x2b, 0xc3, 0x0d, 0xb4,
	0x85, 0x2f, 0x97, 0x7f, 0xfb, 0x7f, 0x78, 0x1d, 0x7d, 0xee, 0x40, 0x41, 0x0e, 0x92, 0x2a, 0xce,
	0xf4, 0xae, 0x76, 0x0d, 0x2f, 0x75, 0x9d, 0xcf, 0xa0, 0x92, 0xb4, 0x67, 0xd4, 0xc4, 0x2b, 0xdd,
	0xbc, 0xdd, 0xc0, 0xcb, 0xbd, 0x7b, 0xcf, 0x38, 0x28, 0xbc, 0xce, 0xcd, 0x4e, 0x4f, 0x4b, 0xf2,
	0x2f, 0xd7, 0xa3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xc4, 0x5b, 0xdc, 0x82, 0x0d, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BananaServiceClient is the client API for BananaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BananaServiceClient interface {
	NewGame(ctx context.Context, in *NewGameRequest, opts ...grpc.CallOption) (*NewGameResponse, error)
	ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error)
	StreamGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (BananaService_StreamGamesClient, error)
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (BananaService_JoinGameClient, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (BananaService_StreamLogsClient, error)
	UpdateBoard(ctx context.Context, in *UpdateBoardRequest, opts ...grpc.CallOption) (*UpdateBoardResponse, error)
	Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*DumpResponse, error)
	Spectate(ctx context.Context, in *SpectateRequest, opts ...grpc.CallOption) (BananaService_SpectateClient, error)
}

type bananaServiceClient struct {
	cc *grpc.ClientConn
}

func NewBananaServiceClient(cc *grpc.ClientConn) BananaServiceClient {
	return &bananaServiceClient{cc}
}

func (c *bananaServiceClient) NewGame(ctx context.Context, in *NewGameRequest, opts ...grpc.CallOption) (*NewGameResponse, error) {
	out := new(NewGameResponse)
	err := c.cc.Invoke(ctx, "/BananaService/NewGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error) {
	out := new(ListGamesResponse)
	err := c.cc.Invoke(ctx, "/BananaService/ListGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) StreamGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (BananaService_StreamGamesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BananaService_serviceDesc.Streams[0], "/BananaService/StreamGames", opts...)
	if err != nil {
		return nil, err
	}
	x := &bananaServiceStreamGamesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BananaService_StreamGamesClient interface {
	Recv() (*GamesList, error)
	grpc.ClientStream
}

type bananaServiceStreamGamesClient struct {
	grpc.ClientStream
}

func (x *bananaServiceStreamGamesClient) Recv() (*GamesList, error) {
	m := new(GamesList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bananaServiceClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, "/BananaService/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (BananaService_JoinGameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BananaService_serviceDesc.Streams[1], "/BananaService/JoinGame", opts...)
	if err != nil {
		return nil, err
	}
	x := &bananaServiceJoinGameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BananaService_JoinGameClient interface {
	Recv() (*GameUpdate, error)
	grpc.ClientStream
}

type bananaServiceJoinGameClient struct {
	grpc.ClientStream
}

func (x *bananaServiceJoinGameClient) Recv() (*GameUpdate, error) {
	m := new(GameUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bananaServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (BananaService_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BananaService_serviceDesc.Streams[2], "/BananaService/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &bananaServiceStreamLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BananaService_StreamLogsClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type bananaServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *bananaServiceStreamLogsClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bananaServiceClient) UpdateBoard(ctx context.Context, in *UpdateBoardRequest, opts ...grpc.CallOption) (*UpdateBoardResponse, error) {
	out := new(UpdateBoardResponse)
	err := c.cc.Invoke(ctx, "/BananaService/UpdateBoard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*DumpResponse, error) {
	out := new(DumpResponse)
	err := c.cc.Invoke(ctx, "/BananaService/Dump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) Spectate(ctx context.Context, in *SpectateRequest, opts ...grpc.CallOption) (BananaService_SpectateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BananaService_serviceDesc.Streams[3], "/BananaService/Spectate", opts...)
	if err != nil {
		return nil, err
	}
	x := &bananaServiceSpectateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BananaService_SpectateClient interface {
	Recv() (*SpectateUpdate, error)
	grpc.ClientStream
}

type bananaServiceSpectateClient struct {
	grpc.ClientStream
}

func (x *bananaServiceSpectateClient) Recv() (*SpectateUpdate, error) {
	m := new(SpectateUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BananaServiceServer is the server API for BananaService service.
type BananaServiceServer interface {
	NewGame(context.Context, *NewGameRequest) (*NewGameResponse, error)
	ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error)
	StreamGames(*ListGamesRequest, BananaService_StreamGamesServer) error
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	JoinGame(*JoinGameRequest, BananaService_JoinGameServer) error
	StreamLogs(*StreamLogsRequest, BananaService_StreamLogsServer) error
	UpdateBoard(context.Context, *UpdateBoardRequest) (*UpdateBoardResponse, error)
	Dump(context.Context, *DumpRequest) (*DumpResponse, error)
	Spectate(*SpectateRequest, BananaService_SpectateServer) error
}

// UnimplementedBananaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBananaServiceServer struct {
}

func (*UnimplementedBananaServiceServer) NewGame(ctx context.Context, req *NewGameRequest) (*NewGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewGame not implemented")
}
func (*UnimplementedBananaServiceServer) ListGames(ctx context.Context, req *ListGamesRequest) (*ListGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGames not implemented")
}
func (*UnimplementedBananaServiceServer) StreamGames(req *ListGamesRequest, srv BananaService_StreamGamesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamGames not implemented")
}
func (*UnimplementedBananaServiceServer) StartGame(ctx context.Context, req *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (*UnimplementedBananaServiceServer) JoinGame(req *JoinGameRequest, srv BananaService_JoinGameServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinGame not implemented")
}
func (*UnimplementedBananaServiceServer) StreamLogs(req *StreamLogsRequest, srv BananaService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (*UnimplementedBananaServiceServer) UpdateBoard(ctx context.Context, req *UpdateBoardRequest) (*UpdateBoardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBoard not implemented")
}
func (*UnimplementedBananaServiceServer) Dump(ctx context.Context, req *DumpRequest) (*DumpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dump not implemented")
}
func (*UnimplementedBananaServiceServer) Spectate(req *SpectateRequest, srv BananaService_SpectateServer) error {
	return status.Errorf(codes.Unimplemented, "method Spectate not implemented")
}

func RegisterBananaServiceServer(s *grpc.Server, srv BananaServiceServer) {
	s.RegisterService(&_BananaService_serviceDesc, srv)
}

func _BananaService_NewGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).NewGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BananaService/NewGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).NewGame(ctx, req.(*NewGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_ListGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).ListGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BananaService/ListGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).ListGames(ctx, req.(*ListGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_StreamGames_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListGamesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BananaServiceServer).StreamGames(m, &bananaServiceStreamGamesServer{stream})
}

type BananaService_StreamGamesServer interface {
	Send(*GamesList) error
	grpc.ServerStream
}

type bananaServiceStreamGamesServer struct {
	grpc.ServerStream
}

func (x *bananaServiceStreamGamesServer) Send(m *GamesList) error {
	return x.ServerStream.SendMsg(m)
}

func _BananaService_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BananaService/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_JoinGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinGameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BananaServiceServer).JoinGame(m, &bananaServiceJoinGameServer{stream})
}

type BananaService_JoinGameServer interface {
	Send(*GameUpdate) error
	grpc.ServerStream
}

type bananaServiceJoinGameServer struct {
	grpc.ServerStream
}

func (x *bananaServiceJoinGameServer) Send(m *GameUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _BananaService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BananaServiceServer).StreamLogs(m, &bananaServiceStreamLogsServer{stream})
}

type BananaService_StreamLogsServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type bananaServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *bananaServiceStreamLogsServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _BananaService_UpdateBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).UpdateBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BananaService/UpdateBoard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).UpdateBoard(ctx, req.(*UpdateBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_Dump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).Dump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BananaService/Dump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).Dump(ctx, req.(*DumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_Spectate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SpectateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BananaServiceServer).Spectate(m, &bananaServiceSpectateServer{stream})
}

type BananaService_SpectateServer interface {
	Send(*SpectateUpdate) error
	grpc.ServerStream
}

type bananaServiceSpectateServer struct {
	grpc.ServerStream
}

func (x *bananaServiceSpectateServer) Send(m *SpectateUpdate) error {
	return x.ServerStream.SendMsg(m)
}

var _BananaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BananaService",
	HandlerType: (*BananaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewGame",
			Handler:    _BananaService_NewGame_Handler,
		},
		{
			MethodName: "ListGames",
			Handler:    _BananaService_ListGames_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _BananaService_StartGame_Handler,
		},
		{
			MethodName: "UpdateBoard",
			Handler:    _BananaService_UpdateBoard_Handler,
		},
		{
			MethodName: "Dump",
			Handler:    _BananaService_Dump_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGames",
			Handler:       _BananaService_StreamGames_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "JoinGame",
			Handler:       _BananaService_JoinGame_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _BananaService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Spectate",
			Handler:       _BananaService_Spectate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "banana.proto",
}
